name: Instagram Poster

on:
  schedule:
    - cron: '0 8,14,20 * * *'
  workflow_dispatch: # Adiciona a capacidade de executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python scheduler.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
